name: Mario Witte
favicon: null
layout_spectrum: 0.15778
typography_spectrum: 0.9007936043199152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-57597-10
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cefeff'
    - '#000000'
    - '#c69e4c'
    - '#4e675b'
    - '#79cedd'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.6719054849818349
  rhythmicContrast: 0.6194200976751745
purpose: []
