name: Mario Witte
favicon: null
layout_spectrum: 0.6587360731791705
typography_spectrum: 0.9007936043199152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-57597-10
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.27098044008016586
  lightness: 0.6051408965140581
  saturation: 0.6719054849818349
  rhythmicContrast: 0.6194200976751745
purpose: []
